// Generated by ts-to-zod
import {z} from 'zod';

export const showInterfaceResponseSchema = z.record(
  z.string(),
  z.object({
    id: z.string(),
    defaultgw: z.boolean().optional(),
    address: z.string().optional(),
  }),
);
